MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;

using PagedList;
using PagedList.Mvc;
namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        // GET: BookStore
        dbQLBansachDataContext data = new dbQLBansachDataContext();
        
        private List<SACH> Laysachmoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }

        public ActionResult Index( int ? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var sachmoi = Laysachmoi(15);
            return View(sachmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult SPTheochude(int id) {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
        }
    }
}

MvcBookStore/Controllers/NguoidungController.cs
using MvcBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;

namespace MvcBookStore.Controllers
{
    public class NguoidungController : Controller
    {
        dbQLBansachDataContext db = new dbQLBansachDataContext();
        // GET: Nguoidung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection,KHACHHANG kh)
        {
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);
            if(String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Yêu cầu nhập lại mật khẩu";
            }
            else if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi5"] = "Phải nhập địa chỉ";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi6"] = "Phải nhập email";
            }
            else if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi7"] = "Phải nhập điện thoại";
            }
            else
            {
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);
                db.KHACHHANGs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if(String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if(String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else 
            {
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
                if (kh != null)
                {
                    Session["Taikhoan"] = kh;
                    return RedirectToAction("GioHang","Giohang");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

MvcBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcBookStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MiChu Books Shop - Nâng tầm tri thức</title>
    <meta name="keywords" content="free website template, flower shop, website templates, CSS, HTML" />
    <meta name="description" content="Flower Shop - free website template, W3C compliant HTML CSS layout" />
    <link href="~/Content/templatemo_style.css" rel="stylesheet" type="text/css" />
    <script src="~/tinymce_6.4.2/tinymce_6.4.2/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({selector:'textarea'})</script>
</head>
<body>
    <div id="templatemo_container">
        <div id="templatemo_top_panel">
            <div id="templatemo_language_section">
                <a href="#"><img src="~/images/templatemo_flag_01.gif" alt="flag 1" /></a>
                <a href="#"><img src="~/images/templatemo_flag_02.gif" alt="flag 2" /></a>
                <a href="#"><img src="~/images/templatemo_flag_03.gif" alt="flag 3" /></a>
                <a href="#"><img src="~/images/templatemo_flag_04.gif" alt="flag 4" /></a>
                <a href="#"><img src="~/images/templatemo_flag_05.gif" alt="flag 5" /></a>
            </div>
            <div id="templatemo_shopping_cart">
                Shopping Cart <span>(<a href="#">3 items</a>)</span>
            </div>
        </div>

        <div id="templatemo_header">
            <img src="~/images/logo2.jpg" width="15%" height="90px" alt="Books Shop" />
        </div>

        <div id="templatemo_banner">
            <a href="#"><img src="~/images/sach2.jpg" width="950px" height="200px" alt="Flower Shop - Free Web Template" title="Flower Shop - Free Web Template" border="0" /></a>

        </div>

        <div id="templatemo_menu_panel">
            <ul>
                <li>
                    @Html.ActionLink("TRANG CHỦ", "Index", "BookStore")
                </li>
                <li>
                    @Html.ActionLink("Quản lý chủ đề", "Sanpham", "Admin")
                </li>
                <li>
                    @Html.ActionLink("Quản lý NXB", "Nhaxuatban", "Admin")
                </li>
                <li>
                    @Html.ActionLink("Quản lý sách", "Sach", "Admin")
                </li>
                

            </ul>
        </div> <!-- end of menu -->

        <div id="templatemo_content">

            <div id="templatemo_content_left">
                <h1>Chào mừng đến với tiệm sách chúng tôi</h1>
                <p>"Cái gọi là duyên phận, chính là trong ngàn vạn người gặp được người cần gặp, trong ngàn vạn năm, giữa mênh mông hoang hoải vô tận của thời gian, không sớm một bước cũng không muộn một bước." </p>
                <p>
                    Một cuốn sách hay không vẽ ra những điều hoang tưởng nó chữa lành tâm hồn cho con người, hướng chúng ta đến những điều tốt đẹp của cuộc sống, nơi đó chúng ta được yêu, được vì nhau, được xúc cảm cùng nhân vật.
                    Hãy để chúng xóa nhòa đi cái tiêu cực của cuộc sống, cũng hãy để chúng ta yêu lấy bản thân mình thêm một chút.
                </p>
                <div class="cleaner_with_height">&nbsp;</div>


                <div>
                    @RenderBody()
                </div>


                <div class="cleaner_with_height">&nbsp;</div>
            </div> <!-- end of ocntent left -->

            <div id="templatemo_content_right">
                <div class="templatemo_right_section">
                    <h4>Search</h4>
                    <div class="templatemo_right_section_content">
                        <form method="get" action="#">
                            <input name="keyword" type="text" id="keyword" />
                            <input type="submit" name="submit" class="button" value="Search" />
                        </form>
                    </div>
                </div>

                <div class="templatemo_right_section">
                    <h4>Chủ đề sách</h4>
                    <div class="templatemo_right_section_content">
                        @Html.Action("Chude", "BookStore")
                    </div>
                </div>

                <div class="templatemo_right_section">
                    <h4>Nhà xuất bản</h4>
                    <div class="templatemo_right_section_content">
                        @Html.Action("Nhaxuatban", "BookStore")
                    </div>
                </div>
            </div> <!-- end of content right-->

            <div class="cleaner">&nbsp;</div>
        </div>
        <div id="templatemo_footer_panel">
            <div id="footer_left">
                <img src="~/images/mastercard.gif" alt="Master Card" /><img src="~/images/visa.gif" alt="Visa Card" /><img src="~/images/paypal.gif" alt="PayPal" /><img src="~/images/verisignsecured.gif" alt="Verisign Secured" />
            </div>
            <div id="footer_right">
                <a>Nguyễn Lê Thảo Quyên - 0950080137</a><br />
                <a href="https://www.facebook.com/quyen.nguyenlethao.5" target="_parent">Facebook</a> <br />
                <a>Liên hệ: 0834191498</a><br />
                <a>Chào mừng và cảm ơn đến với của hàng chúng tôi</a>
            </div>

            <div class="cleaner">&nbsp;</div>
        </div>
    </div>

</body>
</html>

MvcBookStore/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MiChu Books Shop - Nâng tầm tri thức</title>
    <meta name="keywords" content="free website template, flower shop, website templates, CSS, HTML" />
    <meta name="description" content="Flower Shop - free website template, W3C compliant HTML CSS layout" />
    <link href="~/Content/templatemo_style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
    <body>
        <div id="templatemo_container">
            <div id="templatemo_top_panel">
                <div id="templatemo_language_section">
                    <a href="#"><img src="~/images/templatemo_flag_01.gif" alt="flag 1" /></a>
                    <a href="#"><img src="~/images/templatemo_flag_02.gif" alt="flag 2" /></a>
                    <a href="#"><img src="~/images/templatemo_flag_03.gif" alt="flag 3" /></a>
                    <a href="#"><img src="~/images/templatemo_flag_04.gif" alt="flag 4" /></a>
                    <a href="#"><img src="~/images/templatemo_flag_05.gif" alt="flag 5" /></a>
                </div>
                <div id="templatemo_shopping_cart">
                    Shopping Cart <span>(<a href="#">3 items</a>)</span>
                </div>
            </div>

            <div id="templatemo_header">
                <img src="~/images/logo2.jpg" width="15%" height="90px" alt="Books Shop" />
            </div>
            
            <div id="templatemo_banner">
                <a href="#"><img src="~/images/sach2.jpg" width="950px" height="200px" alt="Flower Shop - Free Web Template" title="Flower Shop - Free Web Template" border="0" /></a>
                
            </div>

            <div id="templatemo_menu_panel">
                <ul>
                    <li>
                        @Html.ActionLink("TRANG CHỦ","Index","BookStore")
                    </li>
                    <li>
                        @Html.ActionLink("ĐĂNG KÝ","Dangky","Nguoidung")
                    </li>
                    <li>
                        @Html.ActionLink("ĐĂNG NHẬP", "Dangnhap","Nguoidung")
                    </li>
                    <li>
                        @Html.Action("GiohangPartial","Giohang")
                    </li>
                  
                </ul>
            </div> <!-- end of menu -->

            <div id="templatemo_content">

                <div id="templatemo_content_left">
                    <h1>Chào mừng đến với tiệm sách chúng tôi</h1>
                    <p>"Cái gọi là duyên phận, chính là trong ngàn vạn người gặp được người cần gặp, trong ngàn vạn năm, giữa mênh mông hoang hoải vô tận của thời gian, không sớm một bước cũng không muộn một bước." </p>
                    <p> Một cuốn sách hay không vẽ ra những điều hoang tưởng nó chữa lành tâm hồn cho con người, hướng chúng ta đến những điều tốt đẹp của cuộc sống, nơi đó chúng ta được yêu, được vì nhau, được xúc cảm cùng nhân vật.
                    Hãy để chúng xóa nhòa đi cái tiêu cực của cuộc sống, cũng hãy để chúng ta yêu lấy bản thân mình thêm một chút.</p>
                    <div class="cleaner_with_height">&nbsp;</div>


                    <div>
                        @RenderBody()
                    </div>


                    <div class="cleaner_with_height">&nbsp;</div>
                </div> <!-- end of ocntent left -->

                <div id="templatemo_content_right">
                    <div class="templatemo_right_section">
                        <h4>Search</h4>
                        <div class="templatemo_right_section_content">
                            <form method="get" action="#">
                                <input name="keyword" type="text" id="keyword" />
                                <input type="submit" name="submit" class="button" value="Search" />
                            </form>
                        </div>
                    </div>

                    <div class="templatemo_right_section">
                        <h4>Chủ đề sách</h4>
                        <div class="templatemo_right_section_content">
                           @Html.Action("Chude","BookStore")
                        </div>
                    </div>

                    <div class="templatemo_right_section">
                        <h4>Nhà xuất bản</h4>
                        <div class="templatemo_right_section_content">
                            @Html.Action("Nhaxuatban", "BookStore")                         
                        </div>
                    </div>
                </div> <!-- end of content right-->

                <div class="cleaner">&nbsp;</div>
            </div>
            <div id="templatemo_footer_panel">
                <div id="footer_left">
                    <img src="~/images/mastercard.gif" alt="Master Card" /><img src="~/images/visa.gif" alt="Visa Card" /><img src="~/images/paypal.gif" alt="PayPal" /><img src="~/images/verisignsecured.gif" alt="Verisign Secured" />
                </div>
                <div id="footer_right">
                    <a>Nguyễn Lê Thảo Quyên - 0950080137</a><br />
                    <a href="https://www.facebook.com/quyen.nguyenlethao.5" target="_parent">Facebook</a> <br/>
                    <a>Liên hệ: 0834191498</a><br/>
                    <a>Chào mừng và cảm ơn đến với của hàng chúng tôi</a>
                </div>

                <div class="cleaner">&nbsp;</div>
            </div>
        </div>
        
    </body>
</html>